### PR TITLE
Close Slack

### PR DESCRIPTION
**Pull request by eric-unc**
😢

### CODE REVIEW

**Comment by DereC4** [comment]
Random, but are you the person who made that one Minecraft Forge mod adding the no fall damage shoes from the Portal video games?

**Comment by eric-unc** [comment]
No, but I ported it and currently maintain it.

**Review by ewang2002 — APPROVED** [review]
Looks good, thanks!

**Comment by DereC4** [comment]
> No, but I ported it and currently maintain it.

oh dang that's pretty cool; i remember playing those mods and industrial craft around the 1.12 days! 

I've actually developed a few myself back in high school (although not to such a scale that it got millions of downloads lol) and it's cool how you can apply programming skills to a video game like Minecraft

**Comment by eric-unc** [comment]
Thanks :) modding got me into programming almost a decade ago so I'm glad I did it. The microcelebrity status hasn't translated into getting a solid internship this cycle unfortunately, but it's cool to occasionally meet someone who's used something I made/contributed to and it gets a little bit of extra money.

**Comment by DereC4** [comment]
ye; it's interesting how that stuff seems so long ago from when we were younger but still is fun today. Best of luck on internships; as a freshman all the rejection emails are numbing my sense lol

**Pull request merged**
