### PR TITLE
Just wondering, was my commit "Close Meta and edit Samsung" 

### PR DESCRIPTION
**Pull request by johnli25**
Was my commit (id = 30f49f8b3e709b5ac2e8df1a1755bd4690919458) pushed and merged into the main pittcsc/Summer2023-Internships branch? On my end, my personal forked branch on this repo (which you can view on my profile) says "it's behind by 4 commits."

P.S. I'm not sure how else to message you, so this pull request was the only way I can think of reaching out (lol). Hopefully, this gets resolved. Thanks!

### CODE REVIEW

**Comment by ewang2002** [comment]
@johnli25 Hey! Next time, you can just create an [issue](https://github.com/pittcsc/Summer2023-Internships/issues) :) 

I do see [this PR](https://github.com/pittcsc/Summer2023-Internships/pull/1818) from you which has the right commit message and hash. 

On your side, be sure to sync your fork before you make any changes to your fork. There should be a `Sync Fork` button that you can use.

image

**Comment by johnli25** [comment]
@ewang2002 Sounds good thanks! I sync forked, so it's now saying "this branch (mine) is 4 commits ahead of pittcsc:dev." Any way to fix this? (Also, this means there are no problems with the main pittcsc:dev branch right? Just want to make sure I didn't screw up anything from before)

**Comment by owini** [comment]
Hi, John,

If your branch is 4 commits ahead of main, that means you have changes to your version of the project that the main doesn't have. 

Now you can create a PR to contribute your version and @ewang2002, me, or one of the other admin can review it. Main branch is good and doesn't get changed if you sync changes in main to your version. 

Hope that helps! Please send any updates or questions our way. Thanks!

**Comment by ewang2002** [comment]
> Hope that helps! Please send any updates or questions our way. Thanks!

(Preferably as an issue next time!)

**Pull request closed without merging**
