### PR TITLE
Updated positions at HRT

### PR DESCRIPTION
**Pull request by Dhananjayan-PN**
Updated available positions at HRT

### CODE REVIEW

**Comment by jrbjrb1212** [comment]
Might wanna update your commit to include both SWE and Algo Dev positions

**Comment by Dhananjayan-PN** [comment]
It already says Algo Dev and SWE. Do you mean links to both applications? Because there are 3 applications (3 locations) for each

**Comment by jrbjrb1212** [comment]
Yes links to both Algo Dev and SWE. In location, put Austin, Chicago, and NYC. Kinda like the D. E. Shaw & Co. in the repo

**Comment by cjzheng01** [comment]
LGTM

**Pull request merged**
