### PR TITLE
Fix Optiver Internship location

### PR DESCRIPTION
**Pull request by gryder8**
Looks like this posting is aimed at European students as it asks that you're based in Europe, so it might not belong on this list

### CODE REVIEW

**Comment by jaygupt** [comment]
Maybe this [one](https://www.optiver.com/working-at-optiver/career-opportunities/5674025002/) can be used for US students?

**Comment by gryder8** [comment]
Maybe, although it did say "Located in Europe" in the "Who You Are" section

**Comment by jaygupt** [comment]
In the link I sent or the original one?

**Comment by owini** [comment]
Hi! Thank you both, @gryder8 and @jaygupt! We'll update and use the US-based link.

**Pull request closed without merging**
