### PR TITLE
close Avanade

### PR DESCRIPTION
**Pull request by shlokj**

### CODE REVIEW

**Review by ewang2002 — CHANGES_REQUESTED** [review]
Are you sure Avanade is closed? I was able to apply to it a few minutes ago:

image

image

I'll wait a few hours and check again to see if it's closed.

**Comment by owini** [comment]
Think it's still open.

**Comment by owini** [comment]
Thanks anyway!

**Comment by shlokj** [comment]
whoops, the link was broken when i clicked on it so i assumed it was closed. my bad!

**Comment by ewang2002** [comment]
Don't worry about it! :)

**Pull request closed without merging**
