### PR TITLE
Close PayPal

### PR DESCRIPTION
**Pull request by NoahBres**
CleanShot 2022-10-15 at 02 41 14@2x

### CODE REVIEW

**Review by ewang2002 — CHANGES_REQUESTED** [review]
Hi! Are you sure PayPal is closed? 

When I checked, I saw this

image

and this

image


Additionally, your formatting is off. Your formatting should look like

```
| Paypal | Multiple Locations in United States | **🔒 Closed 🔒** Software Engineer Intern |
```

**Comment by NoahBres** [comment]
If you click the "Apply" button it will link you to the "Page does not exist"

**Comment by ewang2002** [comment]
> If you click the "Apply Now" button it will link you to the "Page does not exist"

The "Apply Now" button leads me to the second screenshot.

Let me try applying to PayPal right now.

**Comment by ewang2002** [comment]
I was able to apply to PayPal.

image

That's weird that it shows it's closed for you, though.

**Comment by NoahBres** [comment]
Huh really interesting. 
Apologies! Thank you so much!

**Comment by ewang2002** [comment]
Don't worry too much about it, though. I've seen occurrences of this happening before with other internship positions!

Thanks again for your help :)

**Pull request closed without merging**
