### PR TITLE
Add Exact-Match.io (Google Auth+Newsletter supported version of inter…

### PR DESCRIPTION
**Pull request by CoderJeffrey**
Dear Pittcsc Repository maintainers,

I have been an loyal user of this repository, which has been a great asset in tracking up-to-date internship postings. This experience has spurred me to think about innovative ways to further optimize and streamline the internship hunting process. The outcome is a new tool I'd like to introduce: [exact-match.io](https://exact-match.io/).

Though it bears some resemblance to interning.dev from a previous PR, exact-match.io introduces the following unique features:

Personalized Profile Creation: Recognizing that each individual's profile and requirements are unique - whether that's needing sponsorship or being at a specific stage in their academic career - users can now tailor their own profile on our [profile/email page](https://exact-match.io/email) after logging in.

Weekly Newsletter: Users can subscribe to receive a weekly newsletter containing newly opened internship positions that match their customized profiles.

Customizable Filter Bar: On the main dashboard, users can select criteria that match their profile, thereby filtering and displaying only the positions that are tailored to their preferences.

Google Authentication: For enhanced security and user convenience, we've integrated Google Authentication, which also enables profile storage on our cloud database.

I believe that these features not only elevate the user experience but also make the internship search process more efficient. I look forward to your thoughts and feedback on exact-match.io.

### CODE REVIEW

**Comment by ewang2002** [comment]
Thanks for your pull request. Based on @tianyizheng02's [response](https://github.com/pittcsc/Summer2024-Internships/pull/1951#issuecomment-1586399467) to that project, for the same reason that was mentioned (last paragraph), I won't merge this PR in, but I'll keep it open for visibility. 

You mentioned feedback, so here's some feedback based on a cursory glance at your website.
- Some locations are kind of hard to read (e.g., see Certik, which has `NYC, NY Seattle, WA SF Bay Area, CA Remote`).
- Seems like your list is missing some entries from our list (e.g., Apple or DE Shaw). This could be a parsing problem.
- The home button at the bottom doesn't seem to do anything.
- The "About" and "Team" buttons at the bottom require me to scroll up once I navigate to said page. The "Contact" button requires me to scroll down. 

The project looks cool, though, and I can definitely see it being used by many people who use this GitHub repository. Nice work.

**Comment by CoderJeffrey** [comment]
> Thanks for your pull request. Based on @tianyizheng02's [response](https://github.com/pittcsc/Summer2024-Internships/pull/1951#issuecomment-1586399467) to that project, for the same reason that was mentioned (last paragraph), I won't merge this PR in, but I'll keep it open for visibility.
> 
> You mentioned feedback, so here's some feedback based on a cursory glance at your website.
> 
> * Some locations are kind of hard to read (e.g., see Certik, which has `NYC, NY Seattle, WA SF Bay Area, CA Remote`).
> * Seems like your list is missing some entries from our list (e.g., Apple or DE Shaw). This could be a parsing problem.
> * The home button at the bottom doesn't seem to do anything.
> * The "About" and "Team" buttons at the bottom require me to scroll up once I navigate to said page. The "Contact" button requires me to scroll down.
> 
> The project looks cool, though, and I can definitely see it being used by many people who use this GitHub repository. Nice work.

Fix on latest version

- The home button at the bottom doesn't seem to do anything => The home button now directs to the header of the main page
- The "About" and "Team" buttons at the bottom require me to scroll up once I navigate to said page. The "Contact" button requires me to scroll down. => The buttons now direct user to respective parts of the page.

Thank you again for your feedback.

**Comment by Zmwang622** [comment]
Hey @csaye! Impressive work with interning.dev, I know I would've loved to have something similar when I was doing internship recruiting. Unfortunately we're currently not looking to add more partners onto the CSC internship repo, I'll reach out if that ever changes. Again, great work!

**Comment by Zmwang622** [comment]
Hey @CoderJeffrey ! Impressive work with exact-match.io, it's great to see y'all try to differentiate against the other competitors. Unfortunately we're currently not looking to add more partners onto the CSC internship repo, I'll reach out if that ever changes. Again, great work!

**Pull request closed without merging**
