### PR TITLE
update Comcast to closed

### PR DESCRIPTION
**Pull request by psjoel02**
* update Comcast to closed

* Remove Comcast link

---------

### CODE REVIEW

**Review by ewang2002 — APPROVED** [review]
Looks great, thank you so much!

**Comment by ewang2002** [comment]
Oops, do you want me to merge this PR?

**Comment by psjoel02** [comment]
No it's my mistake I thought it was closed but it's not. 😂
Link
<https://jobs.comcast.com/jobs/description/regular?external_or_internal=External&job_id=R352221>

**Comment by ewang2002** [comment]
That looks like a different link than the one currently on the list. You can update the link!

**Comment by ewang2002** [comment]
The current link does appear to not work, though.

**Comment by psjoel02** [comment]
Ok I'll update the link.

**Pull request closed without merging**
