### PR TITLE
Add Pixar SWE Internship

### PR DESCRIPTION
**Pull request by kevjin02**

### CODE REVIEW

**Comment by sanskarfc** [comment]
is the link opening at your end? i am not able to open it here in India

**Review by CoderJeffrey — APPROVED** [review]
The link is valid on my end. I can open it.

**Comment by owini** [comment]
Thanks!

**Comment by CoderJeffrey** [comment]
I double check the page, I can open the link for the career page for the company, however, I cannot access the workday link for this job posting.

**Pull request merged**
