### PR TITLE
Add interning.dev

### PR DESCRIPTION
**Pull request by csaye**
I love using PittCSC to find internships but sometimes it's hard to remember which ones you've already applied to. I made a simple open-source dashboard at [interning.dev](https://www.interning.dev/) to have easy access to the internships list and keep track of which ones I've already done, and I thought other people might find it helpful too!

Star/contribute here! ➡️ [github.com/csaye/interning.dev](https://github.com/csaye/interning.dev)

### CODE REVIEW

**Comment by shrey150** [comment]
+1 this is really useful!

**Comment by terryyLi** [comment]
It’s so great and easy to use! Currently it’s using local storage, would be nice if we can create account and login, but it’s already super good and I noticed you complete everything within hours which is fantastic

**Comment by csaye** [comment]
Thanks @terryyLi! In the interest of collecting as little user data as possible I opted for localstorage in this first version, but if it makes sense in the future auth could be very useful!

**Comment by bztravis** [comment]
+1!

**Comment by Wimbazu** [comment]
+1

**Comment by HariChidam** [comment]
+1

**Comment by kevin1015wang** [comment]
+1

**Comment by elliotfklein** [comment]
+1, this is super useful!

**Comment by juebenjamin** [comment]
+1, very useful, great job :)

**Comment by tianyizheng02** [comment]
Hey @csaye! I'm one of the club officers for Pitt CSC, and I just told the other officers about your dashboard. We all think it's really cool that you made this! It definitely reminds me of the synced Google sheet that we used to maintain, and we think that your dashboard will be just as useful, if not more so.

However, for liability reasons, we'd appreciate it if you could change the domain name. [pittcsc.com](https://www.pittcsc.com/) is *way* too similar to [pittcsc.org](https://pittcsc.org/), which is the club's official website. We don't want people to be accidentally directed to your dashboard when they search for Pitt CSC, or vice versa. Plus, having "Pitt CSC" in the name might make people think that your dashboard was made by and/or endorsed by the club. We just want to make it clear to people that your dashboard is a third-party project and not affiliated with the club or with the University of Pittsburgh. To that end, a name that doesn't explicitly reference Pitt CSC (e.g., internshiptracker.com) would be better.

As for your PR, the other officers and I are mixed as to whether we should allow it. On one hand, your dashboard would definitely help visitors to our repo. On the other, we'd be promoting an unendorsed third-party project. So for now, we'll keep your PR open and undecided, but rest assured that we have no plans to get your project taken down.

**Comment by csaye** [comment]
Hi @tianyizheng02, thanks for your comment! First of all, just want to say that there was no ill intent in registering [pittcsc.com](https://www.pittcsc.com/). This internship list is what 99% of the world thinks of when they think of PittCSC, so I thought it was fitting for the project. I entirely understand your concerns regarding affiliation, although changing the name to something like InternshipTracker would not be very accurate as it is meant for this list specifically. A disclaimer of no affiliation and perhaps a link to the club website would be appropriate though, and I apologize for not adding those initially. For the time being, I will change the name and redirect [pittcsc.com](https://www.pittcsc.com/) to [pittcsc.org](https://pittcsc.org/).

I also understand your mixed feelings on including the dashboard within this repo. While it is a third-party project, I intend for it to never be anything but a fully open-source enhancement on this very helpful curated list. I am hopeful that it could be a way for the community that maintains and uses this list to build something together and help each other out. In the future, perhaps it could even be transferred into the pittcsc org so it is no longer a third-party tool.

I appreciate your openness on this project and I hope we can work something out that is best for everyone!

**Comment by csaye** [comment]
- The project has been fully renamed from [pittcsc.com](https://pittcsc.com) to [interning.dev](https://interning.dev)
- [pittcsc.com](https://pittcsc.com) should now redirect to [pittcsc.org](https://pittcsc.org)
- Added a non-affiliation disclaimer to [interning.dev](https://interning.dev)

**Review by ewang2002 — APPROVED** [review]
I'm not affiliated with Pitt CSC, so I don't think I have the "right" to merge this in, but I do want to say that this looks great -- I wish I had this when I was applying to 2023 internships.

**Comment by csaye** [comment]
Appreciate that @ewang2002! I think it's probably a pretty common problem to have this awesome PittCSC list but no easy built-in way to keep track of it all. Especially later in the year when the number of internships really rack up

**Comment by terryyLi** [comment]
> Appreciate that @ewang2002! I think it's probably a pretty common problem to have this awesome PittCSC list but no easy built-in way to keep track of it all. Especially later in the year when the number of internships really rack up

I think you’ve already done great job, and many people following this discussion can use your app if they like. If to some reason they don’t accept this PR it’s also totally fine it’s just if they can help you to advertise or not, and you don’t need the number of users to prove how great your work it is. In fact I believe your current implementation don’t track number of users directly and it’s not your purpose :) So just want to say thank you for contributing and show your passion in tech & solving people’s problem, we appreciate your kindness for people struggling applying internship. wish you all the best✊

**Comment by YUNGU23** [comment]
I really love it, great job, man.

**Comment by zhenglin-charlie-li** [comment]
fantastic work!

**Comment by bztravis** [comment]
I would love to have the ability to filter table columns!

**Comment by csaye** [comment]
> I would love to have the ability to filter table columns!

I just added that actually! You can now filter by text and by whether you have applied to the internship :)

**Comment by ewang2002** [comment]
> Hey @csaye! I'm one of the club officers for Pitt CSC, and I just told the other officers about your dashboard. We all think it's really cool that you made this! It definitely reminds me of the synced Google sheet that we used to maintain, and we think that your dashboard will be just as useful, if not more so.
> 
> ...
>  
> As for your PR, the other officers and I are mixed as to whether we should allow it. On one hand, your dashboard would definitely help visitors to our repo. On the other, we'd be promoting an unendorsed third-party project. So for now, we'll keep your PR open and undecided, but rest assured that we have no plans to get your project taken down.

Out of curiosity, @tianyizheng02, what stops you guys from creating a separate README file for community contributions & resources and explicitly stating that whatever is in that file isn't endorsed by the club (e.g., explicitly say something like "Pitt CSC does **not** endorse the use of any of the following resources, which are managed by those who are not affiliated with Pitt CSC or the University of Pittsburg itself.")? You could also have contribution guidelines that explicitly mention what is allowed to be on this README and what isn't, and obviously the addition of any third-party resources or projects is at your discretion. Perhaps a bit out of scope, but it's not uncommon to see "big" projects mention other projects -- not because they endorse those projects, but because it serves as an extra resource for people to look at. Analogously, we could have something similar with a separate "page" displaying some various third-party resources that a majority of people using this repository would find beneficial.

**Comment by mcgrath-a** [comment]
> 

Hey @csaye ! just wanted to add that this is so helpful and a great way to add better UX & UI to this already amazing resource.

**Comment by tianyizheng02** [comment]
@csaye Just earlier this week an intern said in my company's internal Slack that they were using their work laptop to apply to internships using interning.dev, so your site is def starting to gain some traction lmao

**Comment by csaye** [comment]
@tianyizheng02 That's great to hear! Glad it's helping some people out :)

**Comment by Zmwang622** [comment]
Hey @csaye! Impressive work with interning.dev, I know I would've loved to have something similar when I was doing internship recruiting. Unfortunately we're currently not looking to add more partners onto the CSC internship repo, I'll reach out if that ever changes. Again, great work!

**Pull request closed without merging**
