### PR TITLE
add asana early career

### PR DESCRIPTION
**Pull request by ArshS1**

### CODE REVIEW

**Review by owini — APPROVED** [review]
Thanks

**Comment by egadb** [comment]
I don't think this job posting is legit. The real Asana job board is this one: https://asana.com/jobs/university-recruiting#jobs

**Comment by ArshS1** [comment]
Not sure, also saw it here:
- https://startup.jobs/nyc-summer-software-engineering-internship-asana-early-career-programs-4602983?utm_campaign=google_jobs_apply&utm_medium=organic&utm_source=google_jobs_apply
- https://simplify.jobs/p/847fb685-1b45-4a50-9392-8a3e2059805c/NYC-Summer-Software-Engineering-Internship?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic

My bad if it's not legit

**Comment by tianyizheng02** [comment]
> I don't think this job posting is legit. The real Asana job board is this one: https://asana.com/jobs/university-recruiting#jobs

@egadb It's _possible_ that it's legit because many companies host their applications on Greenhouse (and selecting a role on their careers pages simply directs you to their Greenhouse applications). However, I can't confirm for certain since https://asana.com/jobs/university-recruiting#jobs doesn't show any open roles. My guess is that the Greenhouse link _is_ legit, but third-party sites like startup.jobs and simplify.jobs are out of date and Asana is no longer hiring for that role.

@ArshS1 In the future, make sure that you can find an application from the company's own careers page first, because third-party sites can easily get out of date.

**Pull request merged**
