### PR TITLE
Add Tower Research Capital QT + QD

### PR DESCRIPTION
**Pull request by matthewlkaplan**

### CODE REVIEW

**Review by sim1029 — APPROVED** [review]
lgtm

**Comment by BoraCeci** [comment]
Hello Everyone,

How can I stop getting all these emails? I’ve been unsubscribed from GitHub, but I still keep getting all them. Can someone remove my email from the list?

Sorry for the inconvenience and keep up the great job y’all!
Bora

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sim1029** [comment]
Unwatch the repository or configure your notification settings on github https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications

**Comment by JamesYL** [comment]
even better is to make a filter on your email settings so you don't get notifications from this repo

**Pull request merged**
