### PR TITLE
Add no sponsorship to MosaicML

### PR DESCRIPTION
**Pull request by ad-world**

### CODE REVIEW

**Comment by tianyizheng02** [comment]
The MosaicML applications don't explicitly say that no sponsorship is available. How were you able to confirm that this is the case?

**Review by owini — APPROVED** [review]

**Comment by owini** [comment]
Thanks

**Comment by ad-world** [comment]
Additional notes say:
- US work authorization is required

Which means they're unable to sponsor

**Comment by ffyuanda** [comment]
> Additional notes say:
> 
> * US work authorization is required
> 
> Which means they're unable to sponsor

I think requiring US work authorization does not necessarily equal no sponsorship is available.

For example, if you are a student holding an F-1 visa, you do have US work authorization under CPT or OPT, _and_ you do need sponsorship if you plan to work under H-1b in the future. 

When filling out a job application, normally "do you have work authorization" and "do you need sponsorship" are 2 separate questions, thus further indicating that they shouldn't be correlated or inferred from each other.

Source: [JOB SEEKING TIPS FOR INTERNATIONAL STUDENTS](https://www.umass.edu/careers/sites/default/files/pdf/IPO%20Job%20Seeking%20Tips%20for%20Intl%20Students%20FOR%20SCREENS.pdf)

**Comment by ad-world** [comment]
> For example, if you are a student holding an F-1 visa, you do have US work authorization under CPT or OPT, and you do need sponsorship if you plan to work under H-1b in the future.

That's valid, but then there should be another indicator to specify not being eligible if you're a Canadian student. Since I'm an intl in Canada, I'm unable to apply to Mosaic since I'm not an F-1 visa holder. This is just because this repository includes Canadian positions as well.

**Comment by ffyuanda** [comment]
> That's valid, but then there should be another indicator to specify not being eligible if you're a Canadian student.

Agree. It should say "US-only internship" or something equivalent.

**Pull request merged**
