### PR TITLE
Fix Spotify and add No sponsorship in Palantir and Lumen

### PR DESCRIPTION
**Pull request by KrishPatel13**
[1). Remove Spotify:](https://github.com/pittcsc/Summer2024-Internships/commit/db607f1d1b1da068d308d38cffed9e6c87570dea) 

2023 Fellowship program not for 2024 Internship

2). add No Sponsorship available for Palantir and Lumen

### CODE REVIEW

**Review by owini — APPROVED** [review]

**Comment by tianyizheng02** [comment]
Reverts #1942

**Comment by tianyizheng02** [comment]
Thanks for the catch @KrishPatel13

**Comment by ffyuanda** [comment]
It seems that Palantir does not state explicitly that they don't sponsor on their website?

**Comment by KrishPatel13** [comment]
@ffyuanda  Thank you for your reply :),

Please see the FAQ on their page: https://www.palantir.com/careers/students/path/#palantir-path-faq

```
I am a student at a Canadian university. Can I apply?

No, unfortunately at this time the Path Internship is only open to students studying at an accredited U.S. university.
```

This implies it is not sponsoring!

**Comment by KrishPatel13** [comment]
image

**Comment by KrishPatel13** [comment]
@ffyuanda
Does this answer your question :) ?

**Comment by ffyuanda** [comment]
> See the FAQ on thier page.
> 
> ```
> I am a student at a Canadian university. Can I apply?
> 
> No, unfortunately at this time the Path Internship is only open to students studying at an accredited U.S. university.
> ```
> 
> This implies it is not sponsoring!

You can't quite imply that from this statement. Sponsorship policy is whole another topic. You can say "US-only position" but not necessarily "No sponsorship available".

Let me put it this way, if this position is marked as "No sponsorship available", that will turn down many potential international students who are studying at a US university from applying to this position. And most of the time (if not all), when a company does not say "No sponsorship is available", international students at US schools do have a chance to work there. 

In fact, international students at US universities _do_ have work authorization under different circumstances; see my response [here](https://github.com/pittcsc/Summer2024-Internships/pull/1945#issuecomment-1585056208).

Not sure if that makes sense.

**Pull request merged**
