### PR TITLE
Added WD, databricks

### PR DESCRIPTION
**Pull request by arnavaghav**

### CODE REVIEW

**Review by owini — APPROVED** [review]

**Comment by owini** [comment]
Thanks!

**Comment by ewang2002** [comment]
Olivia caught me as I was reviewing your changes.

For future reference, please make sure maintainers can edit your pull request. 

In any case, if you find new internship positions for a company that's already on this list, it would be ideal if you can move that company to the bottom of the list so viewers know that there are new positions available.

**Comment by owini** [comment]
In the past, we would update the individual company listing if a position reopened. See your point about adding to the bottom of the list for chronology tho.

**Comment by ewang2002** [comment]
Fair.

It was something experimental I talked to Ming about and was trying. 

Not a big deal, though.

**Pull request merged**
