### PR TITLE
Optiver SWE Intern

### PR DESCRIPTION
**Pull request by Swabhan**

### CODE REVIEW

**Review by owini — APPROVED** [review]
Thanks

**Comment by harvishj** [comment]
Are these positions clashing with those in #1106 ?

**Comment by tianyizheng02** [comment]
> Are these positions clashing with those in #1106 ?

@harvishj Yes they are. We already have these two internships in the repo, so this PR shouldn't have been merged.

**Comment by tianyizheng02** [comment]
@Swabhan Please check to make sure that an internship isn't already in the repo before you make a PR

**Pull request merged**
