### PR TITLE
fixed Capstone Investment Advisors link

### PR DESCRIPTION
**Pull request by gholtzap**

### CODE REVIEW

**Review by ewang2002 — APPROVED** [review]
Thanks for the fix!

**Comment by ewang2002** [comment]
But, it looks like the link has already been fixed.

**Comment by tianyizheng02** [comment]
(more specifically, it was fixed in #1929)

**Comment by gholtzap** [comment]
Sorry about that. On my end it wasn't working. Glad someone else fixed it!

**Comment by ewang2002** [comment]
> Sorry about that. On my end it wasn't working. Glad someone else fixed it!

It's possible you might have an outdated fork. But no worries, thank you anyways! We do appreciate that people are actively checking 🙂

**Pull request closed without merging**
