### PR TITLE
Update Emerson, others

### PR DESCRIPTION
**Pull request by eric-unc**
Maybe wait an hour before merging this because I might do some more changes. (and feel free to reformat/fix stuff as always)

### CODE REVIEW

**Comment by ewang2002** [comment]
@eric-unc Is it ready? 

(Also, feel free to mark your PR as a [draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) if you're still working on it.)

**Comment by eric-unc** [comment]
yeah im tired

**Comment by ewang2002** [comment]
Lol mood.

**Review by ewang2002 — APPROVED** [review]
LGTM

**Pull request merged**
