### PR TITLE
Atos Software Engineering Internship

### PR DESCRIPTION
**Pull request by timoconnnor**

### CODE REVIEW

**Comment by timoconnnor** [comment]
please let me know

**Comment by tianyizheng02** [comment]
@timoconnnor I added the internship's conditions to your entry (part-time, year-round, and immediate start date). They're important to specify because they're different from most tech internships (summer only and full-time). I think it's probably OK to merge, but I'd like to get @owini and @ewang2002's judgments as well.

**Comment by timoconnnor** [comment]
@tianyizheng02 okay sounds good

**Comment by ewang2002** [comment]
> @timoconnnor I added the internship's conditions to your entry (part-time, year-round, and immediate start date). They're important to specify because they're different from most tech internships (summer only and full-time). I think it's probably OK to merge, but I'd like to get @owini and @ewang2002's judgments as well.

I don't think we should add this to the repository solely because it's not a summer internship, which is the main point of the repository. This is better off as an off-season internship. If we want to add this, separate it from the rest of the summer internship postings.

I've indicated that we could do something similar (adding an off-season internship README) in #1917, but no one responded to that so I assumed there was no interest in branching out this repository.

**Comment by tianyizheng02** [comment]
@ewang2002 personally I'm cool with the idea with an off-season internship README. Obviously it's not my place to make these kinds of decisions for the whole repo, so we'd need to get approval from the other officers

**Comment by ewang2002** [comment]
@tianyizheng02 I'm not able to message them, but you are, so please ask them.

Also, I do want to note that Olivia has been adding some off-season internships to the 2023 list, so perhaps there's implicit approval through that?

**Comment by tianyizheng02** [comment]
> @tianyizheng02 I'm not able to message them, but you are, so please ask them.
> 
> Also, I do want to note that Olivia has been adding some off-season internships to the 2023 list, so perhaps there's implicit approval through that?

@ewang2002 I've gotten a thumbs-up from some of the other officers, so we can merge in your PR (with some changes) to add an off-season README

**Comment by simcard0000** [comment]
@tianyizheng02 Any update on the off-season readme page?

Edit: oops I just saw that the latest comment is from a couple of minutes ago LOL

**Comment by tianyizheng02** [comment]
@timoconnnor Please update your fork and add your entry to the new off-season README

**Pull request closed without merging**
