### PR TITLE
Add Twitch

### PR DESCRIPTION
**Pull request by tchan102**

### CODE REVIEW

**Comment by GoodluckH** [comment]
Probably can add that BS only (no masters/PhDs)

**Comment by tchan102** [comment]
> 

Added that, and resolved the merge conflict with new commit

**Comment by owini** [comment]
Thanks!

**Comment by MilesWilson07** [comment]
The link didnt work for me

**Comment by ZhangCreations** [comment]
https://github.com/pittcsc/Summer2023-Internships/issues/1004

**Pull request merged**
