### PR TITLE
Adding Fives' Manufacturing Engineer Intern (Summer 2024)

### PR DESCRIPTION
**Pull request by mtlogs**

### CODE REVIEW

**Review by Sagargupta16 — APPROVED** [review]

**Review by ewang2002 — COMMENTED** [review]
The internships here don't seem to be tech related, but this is up to interpretation. I'll let one of the other collaborators look at this and decide.

**Review by Sagargupta16 — APPROVED** [review]

**Comment by mtlogs** [comment]
Hi! Not quite sure whether the positions I added (Fives and/or Altman Solon) were approved. I saw that they were in the tech industry, so thought they'd be relevant! I can remove them, if need be. 

I just added D.E. Shaw's Software Developer Intern – Summer 2024 position

**Comment by tianyizheng02** [comment]
Hello @metthomassedward! The Fives internship unfortunately doesn't qualify as a "tech internship" for this repo. I wrote a comment on it [here](https://github.com/pittcsc/Summer2024-Internships/pull/1903#issuecomment-1576031315), but in short, "tech internship" for this repo means the kinds of jobs that CS majors do (mostly related to SWE). As such, this typically excludes "pure engineering" roles such as manufacturing engineering.

I think the Altman Solon internship should be OK, as it appears that we've regularly accepted quant analyst roles in the past.

We also already have D.E. Shaw's software developer internship in the repo. However, I believe D.E. Shaw has other internships that you can contribute. In the future, make sure to check that an internship you want to add isn't already in the repo.

**Review by Sagargupta16 — APPROVED** [review]

**Comment by mtlogs** [comment]
@tianyizheng02 thanks so much for these notes! Makes a ton of sense. I'll go ahead and close this pull request and keep that in mind for future ones.

**Pull request closed without merging**
