### PR TITLE
Added mercedes sw intern position

### PR DESCRIPTION
**Pull request by arnavaghav**
Found it recently through linkedin.

### CODE REVIEW

**Review by ewang2002 — COMMENTED** [review]
Going to have @owini or @Zmwang622 look at this PR since I'm not sure if it's directly relevant to the repository's purpose here (target major is EE).

**Comment by arnavaghav** [comment]
Resolved merge conflicts - mckinsey is still open, not sure why it was closed.

**Comment by ewang2002** [comment]
> Resolved merge conflicts - mckinsey is still open, not sure why it was closed.

Sure, feel free to reopen it.

It was closed yesterday evening (I checked around the time I merged #1474), but I guess they reopened it this morning.

**Review by owini — APPROVED** [review]

**Comment by owini** [comment]
Updated--thanks both!

**Pull request merged**
